[Parser][Refactoring] dev/parser2: column 관련 부분 class화
jieon-seol/dynamic pull request #27
Opened 2022-02-17 07:00 UTC by jieon-seol

column 부분을 클래스화 하여
column 추가를 용이하게 하고, 하드코딩 된 부분들을 제거하였습니다

2022-02-17 07:07 UTC, Bammuri requested changes

2022-02-17 07:07 UTC, Bammuri commented on dynamic/Parser.cpp
> +std::string Parser::validCheckColumnData(const string dataStr, const string columnStr) {
매개변수 부분 string은 std namespace가 붙어 있지 않네요 통일이 필요해보입니다.

2022-02-17 07:07 UTC, Bammuri commented on dynamic/Parser.cpp
>  using namespace std;
전역 namespace는 지양하는것이 좋을꺼 같습니다.

2022-02-17 07:10 UTC, jieon-seol commented on dynamic/Parser.cpp
> +std::string Parser::validCheckColumnData(const string dataStr, const string columnStr) {
앗 감사합니다 수정하겠습니다

2022-02-17 07:11 UTC, jieon-seol commented on dynamic/Parser.cpp
>  using namespace std;
헤더파일말고 cpp파일에서는 사용해도 되지 않나요..?
일부러 .h에서 안하고 .cpp에서 하도록 하였는데요
(헤더를 다른 파일에서 include하는 경우에 대비하여)

2022-02-17 07:22 UTC, gee6809 approved these changes
LGTM! TODO 남아있는것들도 추후 지워주세요

2022-02-17 07:26 UTC, Bammuri commented on dynamic/Parser.cpp
>  using namespace std;
필요한 곳에서 std::를 다 붙이고 계셔서요 모두 붙이신다면 해당 namespace가 필요없지 않을까요??

2022-02-17 07:32 UTC, jieon-seol commented on dynamic/Parser.cpp
>  using namespace std;
Parser.cpp 내부에서는 안 붙이도록 수정 중입니다.
생각해보니 Parser.h를 다른데서 include할 일이 없네요;;;
Parser.h에서 using namespace 하는걸로 수정하겠습니다

2022-02-17 07:37 UTC, Bammuri commented on dynamic/Parser.cpp
>  using namespace std;
넵 감사합니다~

2022-02-17 07:38 UTC, gee6809 commented on dynamic/Parser.cpp
>  using namespace std;
DBManager에서 사용하는것으로 알고있습니다. 어쨌든 header file에는 using namespace가 없는게 맞는거 같아요

2022-02-17 07:38 UTC, gee6809 commented on dynamic/Parser.cpp
>  using namespace std;
그냥 string -> std::string으로 다 붙이는게 좋아보입니다!

2022-02-17 07:41 UTC, sky64422 commented on dynamic/Parser.cpp
> +	for (int i = 0; i < (int)COLUMN_NUM::MAX; i++) {
이 valid Check 가 단 한 개의 Query 에서도 여러 번 불리는데, for 문까지 돌면 느리지 않을까 싶기두 한데요.
employeeNumCheck, nameCheck 이런 걸 분리해두고 바로 Call 하는 건 어떤가요?
Checker 를 Factory 형식으로 각 Checker 를 두고 check() 하는 것도 좋구요.

2022-02-17 07:41 UTC, sky64422 commented on dynamic/Parser.h
> +	bool checkValidDataFormat(std::string dataStr) {
오호 여기서 검사하는 건 어떤 거인가요??

2022-02-17 07:48 UTC, jieon-seol commented on dynamic/Parser.cpp
>  using namespace std;
아 그러네요... 다시 수정하겠습니다.

2022-02-17 07:55 UTC, jieon-seol commented on dynamic/Parser.cpp
> +	for (int i = 0; i < (int)COLUMN_NUM::MAX; i++) {
넵 맞습니다. 2차로 반영하도록 하겠습니다

2022-02-17 07:56 UTC, jieon-seol commented on dynamic/Parser.h
> +	bool checkValidDataFormat(std::string dataStr) {
checkValidDataFormat() 함수입니다. 잘못 넣은거라 삭제했습니다;;
매의 눈...이시네요.ㅎㅎ

2022-02-17 08:02 UTC, sky64422 approved these changes
LGTM!

2022-02-17 08:10 UTC, Bammuri commented on dynamic/ParserTest.cpp
> +#if 10
이건 어떤 용도인가요..?

2022-02-17 21:57 UTC, jieon-seol commented
Parser 클래스에서 OperationParser 클래스로 분할하여,
ADD, DEL, SCH, MOD등 Operation별로 별도의 클래스에서 parsing 담당하도록
리팩토링 하였습니다.

merge 후에 다시 PR할 시간이 없을 듯하여, 기존 PR에 이어서 진행하려고 합니다
다시 code review 부탁드립니다!

2022-02-17 22:00 UTC, jieon-seol commented
> LGTM! TODO 남아있는것들도 추후 지워주세요

반영했습니다!!

2022-02-17 22:01 UTC, jieon-seol commented on dynamic/ParserTest.cpp
> +#if 10
test 하면서 구현하는 과정에서 임시로 추가한 것인데, 잘못 커밋되었네요;;
삭제하였습니다

2022-02-17 22:04 UTC, jieon-seol commented on dynamic/Parser.cpp
>  using namespace std;
Parser.h에는 using namespace 없이, std:: 붙여서 사용
Parser.cpp, ParserTest.cpp에서는 using namespace 하고, std::는 붙이지 않는 것으로
코드 정리하였습니다

2022-02-17 22:07 UTC, jieon-seol commented on dynamic/Parser.cpp
> +	for (int i = 0; i < (int)COLUMN_NUM::MAX; i++) {
리팩토링하고 나니
column 관련해서는 기능적인 부분이 줄어들어서 struct로 변경하였습니다

2022-02-18 00:38 UTC, gee6809 approved these changes
더 깔끔해졌네요 LGTM!

2022-02-18 00:44 UTC, Bammuri requested changes
표시한 부분 else를 지워도 될꺼 같은데 어떠세요ㅎㅎ

2022-02-18 00:44 UTC, Bammuri commented on dynamic/Parser.cpp
> +	else return OPERATION_TYPE::MAX;//abnormal case
else

2022-02-18 00:44 UTC, Bammuri commented on dynamic/Parser.cpp
> +	else return OPTION1::MAX;//abnormal case
else

2022-02-18 00:44 UTC, Bammuri commented on dynamic/Parser.cpp
> +	else return OPTION2::MAX;//abnormal case
else

2022-02-18 00:44 UTC, Bammuri commented on dynamic/Parser.cpp
> +	else
else

2022-02-18 00:44 UTC, Bammuri commented on dynamic/Parser.cpp
> +	return COLUMN_NUM::NONE;
여기서는 지워주셨네요ㅎㅎ

2022-02-18 00:44 UTC, Bammuri commented on dynamic/Parser.cpp
> +	else
else

2022-02-18 00:56 UTC, sky64422 approved these changes
Parser 가 Factory 형식으로 변경된 점 좋네요.
시간 부족이라 아쉽지만, 별도의 리뷰였다면 더 좋았겠네요.

2022-02-18 01:02 UTC, Bammuri approved these changes
리펙토링 제대로 하신거 같습니다 factory !! 훨씬 깔끔해졌네요

2022-02-18 01:03 UTC, jieon-seol commented on dynamic/Parser.cpp
> +	else return OPERATION_TYPE::MAX;//abnormal case
반영했습니다!

2022-02-18 01:03 UTC, jieon-seol commented on dynamic/Parser.cpp
> +	else return OPTION2::MAX;//abnormal case
반영했습니다!

2022-02-18 01:03 UTC, jieon-seol commented on dynamic/Parser.cpp
> +	else
반영했습니다!

2022-02-18 01:04 UTC, jieon-seol commented on dynamic/Parser.cpp
> +	else
반영했습니다!

2022-02-18 01:06 UTC, jieon-seol commented
> Parser 가 Factory 형식으로 변경된 점 좋네요. 시간 부족이라 아쉽지만, 별도의 리뷰였다면 더 좋았겠네요.

네ㅠㅠ PR을 나눌까도 고민해봤는데, 오늘 오전에 review 받고 merge하는데 시간이 부족할 수도 있을 거 같아서 어쩔 수 없이 하나로 합쳤습니다ㅠㅠ

2022-02-18 01:07 UTC, merged