Dev/searcher
jieon-seol/dynamic pull request #7
Opened 2022-02-15 23:45 UTC by sky64422

Searcher 추상 가상 클래스를 두고 각 Column 별 Searcher 가 이를 상속받아 search() 추상 메소드 구현.
Searcher Factory 클래스를 통해 어떤 Column Searcher 를 생성할 것인지 담당.
User 는 Searcher Factory 객체를 통해 Searcher 객체를 받아와야 하고, 받아온 Searcher 객체를 통해 search() 사용

2022-02-15 23:47 UTC, sky64422 commented on dynamic/Searcher.cpp
> +	vector<string> splitString(const string& targetStr, const char delimiter) {
옵션에 따라 string 을 분리할 때 공통적으로 사용하는 메소드
(중간 번호, 끝 번호, 이름, 성 등..)

2022-02-15 23:48 UTC, sky64422 commented on dynamic/Searcher.cpp
> +		if (searchName == filterData(info.name, nameOption)) {
비교할 때, DB 에 있는 name 의 경우 옵션 처리 결과와 비교

2022-02-15 23:52 UTC, sky64422 commented on dynamic/Searcher.h
> +class IFactorySearcher {
Searcher 객체 생성을 담당할 Factory 패턴 클래스

2022-02-15 23:53 UTC, sky64422 commented on dynamic/Searcher.cpp
> +Searcher* FactorySearcher::getSearcher(const ParserResult& parserResult) const {
parsing 결과에 따라 searcher 선택

2022-02-15 23:55 UTC, gee6809 commented on dynamic/Searcher.h
> +	virtual std::vector<EmployeeInfo> search(const ParserResult& parserResult) const override;
search는 외부에서 사용하는 메소드니까 public으로 하는게 맞지 않나요?

2022-02-15 23:58 UTC, gee6809 commented on dynamic/Searcher.h
> +		delete pEmployeeNumSearcher_;
이렇게 하면, caller 입장에서,
getSearcher를 사용해서 받은 포인터는
delete을 해주면 안되는게 맞는거죠?

2022-02-16 00:05 UTC, sky64422 commented on dynamic/Searcher.h
> +	virtual std::vector<EmployeeInfo> search(const ParserResult& parserResult) const override;
부모 추상 가상 searcher 클래스의 search 를 public 으로 뒀습니다.
이렇게 하면 부모 클래스를 통한 search call 은 허용되지 않을까요?

2022-02-16 00:08 UTC, sky64422 commented on dynamic/Searcher.h
> +		delete pEmployeeNumSearcher_;
네네 아마 caller 는 factory만 new 를 했고 
searcher 는 직접적으로 new 를 호출하지 않았기 때문에
delete 를 안 하는게 맞지 않을까 싶습니다. 
생성과 해제 모두 한 곳에서 하는 게 좋을 거 같아서요.

대신 factory 는 해제해줘야 할 거 같습니다.

2022-02-16 00:14 UTC, gee6809 commented on dynamic/Searcher.h
> +	virtual std::vector<EmployeeInfo> search(const ParserResult& parserResult) const override;
아 재정의한 함수는 private이여도 부모가 public이면 접근 가능하네요
처음 알았습니다...

2022-02-16 00:42 UTC, Bammuri commented on dynamic/Searcher.h
> +		delete pEmployeeNumSearcher_;
네 오너쉽을 한곳에서 가지는게 추후 유지보수에도 좋을 것으로 보입니다.

2022-02-16 00:49 UTC, Bammuri commented on dynamic/Searcher.cpp
> +	for (auto info : (*pDataBase_)) {
auto for 문을 사용하는 경우에 info값이 변하지 않으면 const까지 붙여주시는게 어떨까요
값복사가 일어나기 떄문에 참조자로 하면 성능이 더욱 좋아질꺼 같습니다.

2022-02-16 00:54 UTC, Bammuri requested changes

2022-02-16 00:54 UTC, Bammuri commented on dynamic/Searcher.h
> +
상속받는 경우 소멸자를 가상함수로 해야 부모클래스의 소멸이 정상적으로 진행되는 것으로 알고 있습니다.

2022-02-16 00:54 UTC, Bammuri commented on dynamic/Searcher.cpp
> +	for (auto info : (*pDataBase_)) {
auto for 문을 사용하는 경우에 info값이 변하지 않으면 const까지 붙여주시는게 어떨까요
값복사가 일어나기 떄문에 참조자로 하면 성능이 더욱 좋아질꺼 같습니다.

2022-02-16 00:59 UTC, sky64422 commented on dynamic/Searcher.cpp
> +	for (auto info : (*pDataBase_)) {
좋은 의견 감사합니다.
수정하겠습니다.

2022-02-16 01:00 UTC, sky64422 commented on dynamic/Searcher.h
> +
좋은 의견 감사합니다.
수정하겠습니다.

2022-02-16 01:06 UTC, sky64422 commented on dynamic/Searcher.h
> +
부모 클래스 소멸자를 virtual 로 선언했습니다. (Line 7)
이를 통해 자식 클래스 소멸자가 호출되도록 했습니다.

2022-02-16 01:07 UTC, sky64422 commented on dynamic/Searcher.cpp
> +	for (auto info : (*pDataBase_)) {
for 문 내 auto 를 모두 const auto& 로 변경하였습니다.

2022-02-16 01:24 UTC, gee6809 approved these changes
LGTM

2022-02-16 01:30 UTC, jieon-seol approved these changes
LGTM

2022-02-16 01:30 UTC, jieon-seol commented on dynamic/Searcher.h
> +	virtual std::vector<EmployeeInfo> search(const ParserResult& parserResult) const override;
Searcher 클래스에서는 search()함수가 public인데 자식Searcher들에서는 private네요..
부모 Searcher 포인터로 받아서 호출하기 때문인가요?
이렇게 하면 부모포인터로 search()가 호출할 수 있나요?
(cpp 알못;;)

2022-02-16 01:30 UTC, jieon-seol commented on dynamic/Searcher.cpp
> +		return pEmployeeNumSearcher_;
OPERATION_TYPE이  ADD일 때는 EmployeeNumSearcher를 리턴하도록 되어있네요.
추후? 리팩토링을 위해서 searchColumn에 "employNum"을 추가해달라고 하신 거인가요?

2022-02-16 01:46 UTC, Bammuri commented on dynamic/Searcher.cpp
> +	for (auto info : (*pDataBase_)) {
감사합니다

2022-02-16 01:46 UTC, Bammuri commented on dynamic/Searcher.h
> +
감사합니다.

2022-02-16 01:47 UTC, Bammuri approved these changes
LGTM

2022-02-16 01:56 UTC, sky64422 commented on dynamic/Searcher.cpp
> +		return pEmployeeNumSearcher_;
네네 EmployeeNumSearcher 를 Return 을 하는데,
이 Searcher 들이 결국 searchColumn, searchData 를 기반으로 동작하다보니 이게 ADD 에서는 안 적혀 있어서
정상 동작하지 않을 거라 예상해서 요청드렸습니다.

2022-02-16 01:57 UTC, merged

2022-02-16 02:13 UTC, jieon-seol commented on dynamic/Searcher.cpp
> +		return pEmployeeNumSearcher_;
넵 요청하신 내용대로 Parser에 반영했습니다